### ISSUE TITLE
No snapshots if none exist?

### ISSUE THREAD

**Issue by tjfoster** [jveldboom/php-aws-snapshots#2]
Hello!

Thank you for this!  Makes it super easy!  Is there a reason why the script won't create snapshots if none exist?  I altered the code and was considering doing a pull request, but it occurred to me that you probably had a purpose for that. :)

if(!$snapshots) {
    self::create($volume_id,$this->options['description']);
    continue;
}

**Comment by jveldboom** [comment]
[This should](https://github.com/jveldboom/php-aws-snapshots/blob/master/snapshots.php#L19) only be false if the json returned from the AWS CLI is invalid or PHP was unable to [decode it here](https://github.com/jveldboom/php-aws-snapshots/blob/master/snapshots.php#L109).

Looking at the code again from a pretty long break from it, I realized that is 100% not clear at all. So I'm open to suggestions or alternate ways to do this.

**Comment by tjfoster** [comment]
That's what I get for not thoroughly reading through the code.  Apparently I am getting false there.  I'll diagnose further and see I can figure out why.  Thanks for the response!

**Comment by jveldboom** [comment]
I would recommend printing out the actual command being run and the response. Should be able to add something like the below code to [line 108](https://github.com/jveldboom/php-aws-snapshots/blob/master/snapshots.php#L106-L108)

```php
echo $cmd;
var_dump($response);
```

**Comment by jveldboom** [comment]
I'm going to close this issue since I have not heard back in 2 weeks. Please feel free to respond below or open a new issue if you need anything else.
